

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn formation_wushu.wsgi:application --bind 0.0.0.0:8000
    # ... inchangé ...
    volumes:
      - ./:/app
      - ./templates:/app/templates
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./formation_wushu/static:/app/formation_wushu/static

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./templates:/app/templates
      - ./media:/app/media
      - ./formation_wushu/static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
