# Generated by Django 5.2.4 on 2025-07-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='consigne',
            field=models.TextField(blank=True, help_text='Consigne pédagogique'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='duree',
            field=models.PositiveIntegerField(help_text='Durée en minutes'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='lien',
            field=models.URLField(blank=True, help_text='Lien complémentaire vers un article, etc.'),
        ),
    ]
