# Generated by Django 5.2.4 on 2025-07-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0002_alter_atelier_consigne_alter_atelier_duree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichepage',
            name='sequences',
        ),
        migrations.AddField(
            model_name='fichepage',
            name='sequences',
            field=models.ManyToManyField(blank=True, to='fiches.sequence'),
        ),
    ]
