# Generated by Django 5.0.14 on 2025-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='repetitions',
            field=models.PositiveIntegerField(blank=True, help_text='Ex\u202f: 12 répétitions/série', null=True, verbose_name='Nombre de répétitions'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='series',
            field=models.PositiveIntegerField(blank=True, help_text='Ex\u202f: 3 séries', null=True, verbose_name='Nombre de séries'),
        ),
    ]
