# Generated by Django 5.0.14 on 2025-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0002_atelier_repetitions_atelier_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='atelier',
            name='materiels',
            field=models.ManyToManyField(blank=True, related_name='ateliers', to='fiches.materiel'),
        ),
    ]
