# Generated by Django 5.0.14 on 2025-08-05 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0003_materiel_atelier_materiels'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepage',
            name='titre',
            field=models.CharField(default=datetime.date(1900, 1, 1), max_length=200),
            preserve_default=False,
        ),
    ]
