# Generated by Django 5.0.14 on 2025-08-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0004_atelier_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='nom',
            field=models.CharField(default='Sans nom', help_text='titre atelier ex: wubuquan, exercice souplesse', max_length=100),
            preserve_default=False,
        ),
    ]
