# Generated by Django 5.0.14 on 2025-08-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0004_fichepage_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichepage',
            name='titre',
        ),
    ]
