# Generated by Django 5.0.14 on 2025-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0005_remove_fichepage_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='ateliers/', verbose_name='Téléverser une image'),
        ),
        migrations.AddField(
            model_name='technique',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='techniques/', verbose_name='Téléverser une image'),
        ),
    ]
